- name: pypi-publish
  uses: pypa/gh-action-pypi-publish@v1.14.0
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
    repository-url: https://upload.pypi.org/legacy/
    packages-dir: dist
    verify-metadata: true
    skip-existing: false
    verbose: true
    print-hash: true
    attestations: false
